using Dapper;
using Npgsql;
using System;
using System.Collections.Generic;
using System.Text;

namespace DataImporter.DBHelpers
{
	public class StudyTableBuildersAD
	{
		string db_conn;

		public StudyTableBuildersAD(string _db_conn)
		{
			db_conn = _db_conn;
		}


		public void create_table_studies(int source_id)
		{
			string sql_string = @"CREATE TABLE IF NOT EXISTS ad.studies(
                ad_id                  INT    GENERATED BY DEFAULT AS IDENTITY (START WITH 2000001) PRIMARY KEY   
			  , sd_id                  VARCHAR         NOT NULL
              , hash_id                CHAR(32)        NOT NULL
			  , display_title          VARCHAR         NULL
              , title_lang_code        VARCHAR         NULL default 'en'
			  , brief_description      VARCHAR         NULL
              , bd_contains_html       BOOLEAN         NULL	default false
			  , data_sharing_statement VARCHAR         NULL
              , dss_contains_html      BOOLEAN         NULL	default false
			  , study_start_year       INT             NULL
			  , study_start_month      INT             NULL
			  , study_type_id          INT             NULL
			  , study_status_id        INT             NULL
			  , study_enrolment        INT             NULL
			  , study_gender_elig_id   INT             NULL
			  , min_age                INT             NULL
			  , min_age_units_id       INT             NULL
			  , max_age                INT             NULL
			  , max_age_units_id       INT             NULL
			  , datetime_of_data_fetch TIMESTAMPTZ     NULL
              , source_id              INT             NOT NULL default " + source_id.ToString() + @"
              , record_hash            CHAR(32)        NULL
              , study_full_hash        CHAR(32)        NULL
              , added_on               TIMESTAMPTZ     NOT NULL default now()
              , exported_on            TIMESTAMPTZ     NULL
              , record_status_id       INT             NOT NULL default 1
			);
            CREATE INDEX studies_sd_id ON ad.studies(sd_id);
            CREATE INDEX studies_hash_id ON ad.studies(hash_id);";

			using (var conn = new NpgsqlConnection(db_conn))
			{
				conn.Execute(sql_string);
			}
		}


		public void create_table_study_identifiers()
		{
			string sql_string = @"CREATE TABLE IF NOT EXISTS ad.study_identifiers(
                ad_id                  INT    GENERATED BY DEFAULT AS IDENTITY (START WITH 10000001) PRIMARY KEY
              , study_ad_id            INT             NULL
              , study_hash_id          CHAR(32)        NULL
			  , sd_id                  VARCHAR         NOT NULL
			  , identifier_value       VARCHAR         NULL
			  , identifier_type_id     INT             NULL
			  , identifier_org_id      INT             NULL
			  , identifier_org         VARCHAR         NULL
			  , identifier_date        VARCHAR         NULL
			  , identifier_link        VARCHAR         NULL
              , record_hash            CHAR(32)        NULL
              , added_on               TIMESTAMPTZ     NOT NULL default now()
              , exported_on            TIMESTAMPTZ     NULL
              , record_status_id       INT             NOT NULL default 1
			);
            CREATE INDEX study_identifiers_study_ad_id ON ad.study_identifiers(study_ad_id);
            CREATE INDEX study_identifiers_sd_id ON ad.study_identifiers(sd_id);
            CREATE INDEX study_identifiers_study_hash_id ON ad.study_identifiers(study_hash_id);";

			using (var conn = new NpgsqlConnection(db_conn))
			{
				conn.Execute(sql_string);
			}
		}


		public void create_table_study_relationships()
		{
			string sql_string = @"CREATE TABLE IF NOT EXISTS ad.study_relationships(
                ad_id                  INT    GENERATED BY DEFAULT AS IDENTITY (START WITH 10000001) PRIMARY KEY
              , study_ad_id            INT             NULL
              , study_hash_id          CHAR(32)        NULL
			  , sd_id                  VARCHAR         NOT NULL
			  , relationship_type_id   INT             NULL
			  , target_sd_id           VARCHAR         NULL
              , target_ad_id           INT             NULL
              , record_hash            CHAR(32)        NULL
              , added_on               TIMESTAMPTZ     NOT NULL default now()
              , exported_on            TIMESTAMPTZ     NULL
              , record_status_id       INT             NOT NULL default 1
			);
            CREATE INDEX study_relationships_study_ad_id ON ad.study_relationships(study_ad_id);
            CREATE INDEX study_relationships_sd_id ON ad.study_relationships(sd_id);
            CREATE INDEX study_relationships_study_hash_id ON ad.study_relationships(study_hash_id);
            CREATE INDEX study_relationships_target_sd_id ON ad.study_relationships(target_sd_id );";

			using (var conn = new NpgsqlConnection(db_conn))
			{
				conn.Execute(sql_string);
			}
		}


		public void create_table_study_references()
		{
			string sql_string = @"CREATE TABLE IF NOT EXISTS ad.study_references(
                ad_id                  INT    GENERATED BY DEFAULT AS IDENTITY (START WITH 10000001) PRIMARY KEY
              , study_ad_id            INT             NULL
              , study_hash_id          CHAR(32)        NULL
			  , sd_id                  VARCHAR         NOT NULL
			  , pmid                   VARCHAR         NULL
			  , citation               VARCHAR         NULL
			  , doi                    VARCHAR         NULL	
			  , comments               VARCHAR         NULL
              , record_hash            CHAR(32)        NULL
              , added_on               TIMESTAMPTZ     NOT NULL default now()
              , exported_on            TIMESTAMPTZ     NULL
              , record_status_id       INT             NOT NULL default 1
			);
            CREATE INDEX study_references_study_ad_id ON ad.study_references(study_ad_id);
            CREATE INDEX study_references_sd_id ON ad.study_references(sd_id);
            CREATE INDEX study_references_study_hash_id ON ad.study_references(study_hash_id);";

			using (var conn = new NpgsqlConnection(db_conn))
			{
				conn.Execute(sql_string);
			}
		}


		public void create_table_study_titles()
		{
			string sql_string = @"CREATE TABLE IF NOT EXISTS ad.study_titles(
                ad_id                  INT    GENERATED BY DEFAULT AS IDENTITY (START WITH 10000001) PRIMARY KEY
              , study_ad_id            INT             NULL
              , study_hash_id          CHAR(32)        NULL
			  , sd_id                  VARCHAR         NOT NULL
			  , title_text             VARCHAR         NULL
			  , title_type_id          INT             NULL
			  , title_lang_code        VARCHAR         NOT NULL default 'en'
			  , lang_usage_id          INT             NOT NULL default 11
			  , is_default             BOOLEAN         NULL
			  , comments               VARCHAR         NULL
			  , comparison_text        VARCHAR         NULL
              , record_hash            CHAR(32)        NULL
              , added_on               TIMESTAMPTZ     NOT NULL default now()
              , exported_on            TIMESTAMPTZ     NULL
              , record_status_id       INT             NOT NULL default 1
			);
            CREATE INDEX study_titles_study_ad_id ON ad.study_titles(study_ad_id);
            CREATE INDEX study_titles_sd_id ON ad.study_titles(sd_id);
            CREATE INDEX study_titles_study_hash_id ON ad.study_titles(study_hash_id);";

			using (var conn = new NpgsqlConnection(db_conn))
			{
				conn.Execute(sql_string);
			}
		}


		public void create_table_study_contributors()
		{
			string sql_string = @"CREATE TABLE IF NOT EXISTS ad.study_contributors(
				ad_id                  INT    GENERATED BY DEFAULT AS IDENTITY (START WITH 10000001) PRIMARY KEY
              , study_ad_id            INT             NULL
              , study_hash_id          CHAR(32)        NULL
			  , sd_id                  VARCHAR         NOT NULL
			  , contrib_type_id        INT             NULL
			  , is_individual          BOOLEAN         NULL
			  , organisation_id        INT             NULL
              , organisation_name      VARCHAR         NULL
			  , person_id              INT             NULL
			  , person_given_name      VARCHAR         NULL
			  , person_family_name     VARCHAR         NULL
			  , person_full_name       VARCHAR         NULL
			  , person_identifier      VARCHAR         NULL
			  , identifier_type        VARCHAR         NULL
			  , person_affiliation     VARCHAR         NULL
			  , affil_org_id           VARCHAR         NULL
			  , affil_org_id_type      VARCHAR         NULL
              , record_hash            CHAR(32)        NULL
              , added_on               TIMESTAMPTZ     NOT NULL default now()
              , exported_on            TIMESTAMPTZ     NULL
              , record_status_id       INT             NOT NULL default 1
			);
            CREATE INDEX study_contributors_study_ad_id ON ad.study_contributors(study_ad_id);
            CREATE INDEX study_contributors_sd_id ON ad.study_contributors(sd_id);
            CREATE INDEX study_contributors_study_hash_id ON ad.study_contributors(study_hash_id);";

			using (var conn = new NpgsqlConnection(db_conn))
			{
				conn.Execute(sql_string);
			}
		}


		public void create_table_study_topics()
		{
			string sql_string = @"CREATE TABLE IF NOT EXISTS ad.study_topics(
				ad_id                  INT    GENERATED BY DEFAULT AS IDENTITY (START WITH 10000001) PRIMARY KEY
              , study_ad_id            INT             NULL
              , study_hash_id          CHAR(32)        NULL
			  , sd_id                  VARCHAR         NOT NULL
			  , topic_type_id          INT             NULL
			  , topic_value            VARCHAR         NULL
			  , topic_ct_id            INT             NULL
			  , topic_ct_code          VARCHAR         NULL
			  , where_found            VARCHAR         NULL
              , record_hash            CHAR(32)        NULL
              , added_on               TIMESTAMPTZ     NOT NULL default now()
              , exported_on            TIMESTAMPTZ     NULL
              , record_status_id       INT             NOT NULL default 1
			);
            CREATE INDEX study_topics_study_ad_id ON ad.study_topics(study_ad_id);
            CREATE INDEX study_topics_sd_id ON ad.study_topics(sd_id);
            CREATE INDEX study_topics_study_hash_id ON ad.study_topics(study_hash_id);";

			using (var conn = new NpgsqlConnection(db_conn))
			{
				conn.Execute(sql_string);
			}
		}


		public void create_table_study_hashes()
		{
			string sql_string = @"CREATE TABLE IF NOT EXISTS ad.study_hashes(
                ad_id                  INT    GENERATED BY DEFAULT AS IDENTITY (START WITH 10000001) PRIMARY KEY
              , study_ad_id            INT             NULL
			  , study_hash_id          CHAR(32)        NULL
			  , sd_id                  VARCHAR         NOT NULL
			  , hash_type_id           INT             NULL
			  , composite_hash         CHAR(32)        NULL
              , added_on               TIMESTAMPTZ     NOT NULL default now()
			);
            CREATE INDEX study_hashes_study_ad_id ON ad.study_hashes(study_ad_id);
            CREATE INDEX study_hashes_sd_id ON ad.study_hashes(sd_id);
            CREATE INDEX study_hashes_study_hash_id ON ad.study_hashes(study_hash_id);";

			using (var conn = new NpgsqlConnection(db_conn))
			{
				conn.Execute(sql_string);
			}
		}
	}


	public class ObjectTableBuildersAD
	{ 
		string db_conn;

		public ObjectTableBuildersAD(string _db_conn)
		{
			db_conn = _db_conn;
		}


	    public void create_table_data_objects(int source_id)
		{
			string sql_string = @"CREATE TABLE IF NOT EXISTS ad.data_objects(
                ad_id                  INT    GENERATED BY DEFAULT AS IDENTITY (START WITH 10000001) PRIMARY KEY
              , study_ad_id            INT             NULL
              , object_hash_id         CHAR(32)        NOT NULL
              , study_hash_id          CHAR(32)        NOT NULL
			  , sd_id                  VARCHAR         NOT NULL
              , do_id                  INT             NOT NULL
			  , display_title          VARCHAR         NULL
			  , doi                    VARCHAR         NULL 
			  , doi_status_id          INT             NULL
			  , publication_year       INT             NULL
			  , object_class_id        INT             NULL
			  , object_type_id         INT             NULL
			  , managing_org_id        INT             NULL
			  , managing_org           VARCHAR         NULL
			  , access_type_id         INT             NULL
			  , access_details         VARCHAR         NULL
			  , access_details_url     VARCHAR         NULL
			  , url_last_checked       DATE            NULL
			  , add_study_contribs     BOOLEAN         NULL
			  , add_study_topics       BOOLEAN         NULL
			  , datetime_of_data_fetch TIMESTAMPTZ     NULL
              , source_id              INT             NOT NULL default " + source_id.ToString() + @"
              , record_hash            CHAR(32)        NULL
              , object_full_hash       CHAR(32)        NULL
              , added_on               TIMESTAMPTZ     NOT NULL default now()
              , exported_on            TIMESTAMPTZ     NULL
              , record_status_id       INT             NOT NULL default 1
			);            
            CREATE INDEX data_objects_study_ad_id ON ad.data_objects(study_ad_id);
            CREATE INDEX data_objects_object_hash_id ON ad.data_objects(object_hash_id);
            CREATE INDEX data_objects_study_hash_id ON ad.data_objects(study_hash_id);";

			using (var conn = new NpgsqlConnection(db_conn))
			{
				conn.Execute(sql_string);
			}
		}


		public void create_table_dataset_properties()
		{
			string sql_string = @"CREATE TABLE IF NOT EXISTS ad.dataset_properties(
                ad_id                  INT    GENERATED BY DEFAULT AS IDENTITY (START WITH 10000001) PRIMARY KEY
              , object_ad_id           INT             NULL
              , object_hash_id         CHAR(32)        NOT NULL
			  , sd_id                  VARCHAR         NOT NULL
              , do_id                  INT             NOT NULL
			  , record_keys_type_id    INT             NULL 
			  , record_keys_details    VARCHAR         NULL    
			  , identifiers_type_id    INT             NULL  
			  , identifiers_details    VARCHAR         NULL    
			  , consents_type_id       INT             NULL  
              , consents_details       VARCHAR         NULL 
              , record_hash            CHAR(32)        NULL
              , added_on               TIMESTAMPTZ     NOT NULL default now()
              , exported_on            TIMESTAMPTZ     NULL
              , record_status_id       INT             NOT NULL default 1
			);            
            CREATE INDEX dataset_properties_study_ad_id ON ad.dataset_properties(object_ad_id);
            CREATE INDEX dataset_properties_object_hash_id ON ad.dataset_properties(object_hash_id);";



			using (var conn = new NpgsqlConnection(db_conn))
			{
				conn.Execute(sql_string);
			}
		}


		public void create_table_object_dates()
		{
			string sql_string = @"CREATE TABLE IF NOT EXISTS ad.object_dates(
                ad_id                  INT    GENERATED BY DEFAULT AS IDENTITY (START WITH 10000001) PRIMARY KEY
              , object_ad_id           INT             NULL
              , object_hash_id         CHAR(32)        NOT NULL
			  , sd_id                  VARCHAR         NOT NULL
              , do_id                  INT             NOT NULL
			  , date_type_id           INT             NULL
			  , is_date_range          BOOLEAN         NULL default false
			  , date_as_string         VARCHAR         NULL
			  , start_year             INT             NULL
			  , start_month            INT             NULL
			  , start_day              INT             NULL
			  , end_year               INT             NULL
			  , end_month              INT             NULL
			  , end_day                INT             NULL
			  , details                VARCHAR         NULL
              , record_hash            CHAR(32)        NULL
              , added_on               TIMESTAMPTZ     NOT NULL default now()
              , exported_on            TIMESTAMPTZ     NULL
              , record_status_id       INT             NOT NULL default 1
			);
            CREATE INDEX object_dates_object_ad_id ON ad.object_dates(object_ad_id);
            CREATE INDEX object_dates_object_hash_id ON ad.object_dates(object_hash_id);";

			using (var conn = new NpgsqlConnection(db_conn))
			{
				conn.Execute(sql_string);
			}
		}


		public void create_table_object_instances()
		{
			string sql_string = @"CREATE TABLE IF NOT EXISTS ad.object_instances(
                ad_id                  INT    GENERATED BY DEFAULT AS IDENTITY (START WITH 10000001) PRIMARY KEY
              , object_ad_id           INT             NULL
              , object_hash_id         CHAR(32)        NOT NULL
			  , sd_id                  VARCHAR         NOT NULL
              , do_id                  INT             NOT NULL
			  , instance_type_id       INT             NOT NULL  default 1
			  , repository_org_id      INT             NULL
			  , repository_org         VARCHAR         NULL
			  , url                    VARCHAR         NULL
			  , url_accessible         BOOLEAN         NULL
			  , url_last_checked       DATE            NULL
			  , resource_type_id       INT             NULL
			  , resource_size          VARCHAR         NULL
			  , resource_size_units    VARCHAR         NULL
              , record_hash            CHAR(32)        NULL
              , added_on               TIMESTAMPTZ     NOT NULL default now()
              , exported_on            TIMESTAMPTZ     NULL
              , record_status_id       INT             NOT NULL default 1
			);
            CREATE INDEX object_instances_object_ad_id ON ad.object_instances(object_ad_id);
            CREATE INDEX object_instances_object_hash_id ON ad.object_instances(object_hash_id);";

			using (var conn = new NpgsqlConnection(db_conn))
			{
				conn.Execute(sql_string);
			}
		}


		public void create_table_object_titles()
		{
			string sql_string = @"CREATE TABLE IF NOT EXISTS ad.object_titles(
                ad_id                  INT    GENERATED BY DEFAULT AS IDENTITY (START WITH 10000001) PRIMARY KEY
              , object_ad_id           INT             NULL
              , object_hash_id         CHAR(32)        NOT NULL
			  , sd_id                  VARCHAR         NOT NULL
              , do_id                  INT             NOT NULL
			  , title_text             VARCHAR         NULL
			  , title_type_id          INT             NULL
			  , title_lang_code        VARCHAR         NOT NULL default 'en'
			  , lang_usage_id          INT             NOT NULL default 11
			  , is_default             BOOLEAN         NULL
			  , comments               VARCHAR         NULL
			  , comparison_text        VARCHAR         NULL
              , record_hash            CHAR(32)        NULL
              , added_on               TIMESTAMPTZ     NOT NULL default now()
              , exported_on            TIMESTAMPTZ     NULL
              , record_status_id       INT             NOT NULL default 1
			);
            CREATE INDEX object_titles_object_ad_id ON ad.object_titles(object_ad_id);
            CREATE INDEX object_titles_object_hash_id ON ad.object_titles(object_hash_id);";

			using (var conn = new NpgsqlConnection(db_conn))
			{
				conn.Execute(sql_string);
			}
		}


		public void create_table_object_contributors()
		{
			string sql_string = @"CREATE TABLE IF NOT EXISTS ad.object_contributors(
                ad_id                  INT    GENERATED BY DEFAULT AS IDENTITY (START WITH 10000001) PRIMARY KEY
              , object_ad_id           INT             NULL
              , object_hash_id         CHAR(32)        NOT NULL
			  , sd_id                  VARCHAR         NOT NULL
              , do_id                  INT             NOT NULL
			  , contrib_type_id        INT             NULL
			  , contrib_type           VARCHAR         NULL
			  , is_individual          BOOLEAN         NULL
			  , organisation_id        INT             NULL
              , organisation_name      VARCHAR         NULL
			  , person_id              INT             NULL
			  , person_given_name      VARCHAR         NULL
			  , person_family_name     VARCHAR         NULL
			  , person_full_name       VARCHAR         NULL
			  , person_identifier      VARCHAR         NULL
			  , identifier_type        VARCHAR         NULL
			  , person_affiliation     VARCHAR         NULL
			  , affil_org_id           VARCHAR         NULL
			  , affil_org_id_type      VARCHAR         NULL
              , record_hash            CHAR(32)        NULL
              , added_on               TIMESTAMPTZ     NOT NULL default now()
              , exported_on            TIMESTAMPTZ     NULL
              , record_status_id       INT             NOT NULL default 1
			);
            CREATE INDEX object_contributors_object_ad_id ON ad.object_contributors(object_ad_id);
            CREATE INDEX object_contributors_object_hash_id ON ad.object_contributors(object_hash_id);";

			using (var conn = new NpgsqlConnection(db_conn))
			{
				conn.Execute(sql_string);
			}
		}


		public void create_table_object_topics()
		{
			string sql_string = @"CREATE TABLE IF NOT EXISTS ad.object_topics(
                ad_id                  INT    GENERATED BY DEFAULT AS IDENTITY (START WITH 10000001) PRIMARY KEY
              , object_ad_id           INT             NULL
              , object_hash_id         CHAR(32)        NOT NULL
			  , sd_id                  VARCHAR         NOT NULL
              , do_id                  INT             NOT NULL
			  , topic_type_id          INT             NULL
			  , topic_type             VARCHAR         NULL
			  , topic_value            VARCHAR         NULL
			  , topic_ct_id            INT             NULL
			  , topic_ct               VARCHAR         NULL
			  , topic_ct_code          VARCHAR         NULL
			  , where_found            VARCHAR         NULL
              , record_hash            CHAR(32)        NULL
              , added_on               TIMESTAMPTZ     NOT NULL default now()
              , exported_on            TIMESTAMPTZ     NULL
              , record_status_id       INT             NOT NULL default 1
			);
            CREATE INDEX object_topics_object_ad_id ON ad.object_topics(object_ad_id);
            CREATE INDEX object_topics_object_hash_id ON ad.object_topics(object_hash_id);";

			using (var conn = new NpgsqlConnection(db_conn))
			{
				conn.Execute(sql_string);
			}
		}


		public void create_table_object_languages()
		{
			string sql_string = @"CREATE TABLE IF NOT EXISTS ad.object_languages(
                ad_id                  INT    GENERATED BY DEFAULT AS IDENTITY (START WITH 10000001) PRIMARY KEY
              , object_ad_id           INT             NULL
              , object_hash_id         CHAR(32)        NOT NULL
			  , sd_id                  VARCHAR         NOT NULL
              , do_id                  INT             NOT NULL
              , lang_code              VARCHAR         NULL default 'en'
              , record_hash            CHAR(32)        NULL
              , added_on               TIMESTAMPTZ     NOT NULL default now()
              , exported_on            TIMESTAMPTZ     NULL
              , record_status_id       INT             NOT NULL default 1
			);
            CREATE INDEX object_languages_object_ad_id ON ad.object_languages(object_ad_id);
            CREATE INDEX object_languages_object_hash_id ON ad.object_languages(object_hash_id);";

			using (var conn = new NpgsqlConnection(db_conn))
			{
				conn.Execute(sql_string);
			}
		}


		public void create_table_object_hashes()
		{
			string sql_string = @"CREATE TABLE IF NOT EXISTS ad.object_hashes(
                ad_id                  INT    GENERATED BY DEFAULT AS IDENTITY (START WITH 10000001) PRIMARY KEY
              , object_ad_id           INT             NULL
              , object_hash_id         CHAR(32)        NULL
			  , study_hash_id          CHAR(32)        NULL
			  , sd_id                  VARCHAR         NOT NULL
              , do_id                  INT             NOT NULL
			  , hash_type_id           INT             NULL
              , composite_hash         CHAR(32)        NULL
              , added_on               TIMESTAMPTZ     NOT NULL default now()
			);
            CREATE INDEX object_hashes_object_ad_id ON ad.object_hashes(object_ad_id);
            CREATE INDEX object_hashes_object_hash_id ON ad.object_hashes(object_hash_id);";

			using (var conn = new NpgsqlConnection(db_conn))
			{
				conn.Execute(sql_string);
			}
		}
	}
}

